import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="importer-lib-campuscom",
    version="1.0.0",
    author="Rezwanul Haque",
    author_email="rezwanul.haque@vivacomsolutions.com",
    description="importer common library for campus.com project",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Rezwanul-Haque-Viva/Importer-lib.git",
    packages=setuptools.find_packages(),
    package_data={'models.states': ['models/states/us_states.yml']},
    include_package_data=True,
    install_requires=[
        "amqp==2.5.2",
        "arrow==0.15.4",
        "astroid==2.3.3",
        "aws-requests-auth==0.4.2",
        "bcrypt==3.1.7",
        "blinker==1.4",
        "boto3==1.11.9",
        "botocore==1.14.6",
        "certifi==2020.4.5.1",
        "cffi==1.13.2",
        "chardet==3.0.4",
        "coloredlogs==10.0",
        "deepmerge==0.1.0",
        "docutils==0.15.2",
        "elasticsearch==7.5.1",
        "ftfy==5.7",
        "humanfriendly==8.1",
        "idna==2.8",
        "importlib-metadata==1.6.0",
        "isort==4.3.21",
        "jmespath==0.9.5",
        "kombu==4.6.7",
        "lazy-object-proxy==1.4.3",
        "mailchecker==3.3.4",
        "mccabe==0.6.1",
        "mongoengine==0.19.1",
        "phonenumbers==8.12.1",
        "pprint==0.1",
        "pycparser==2.19",
        "pydash==4.7.6",
        "pylint==2.4.4",
        "pymongo==3.10.1",
        "python-benedict==0.16.0",
        "python-dateutil==2.8.1",
        "python-dotenv==0.11.0",
        "python-slugify==4.0.0",
        "PyYAML==5.3",
        "redis==3.3.11",
        "requests==2.22.0",
        "ruamel.yaml==0.16.7",
        "ruamel.yaml.clib==0.2.0",
        "s3transfer==0.3.3",
        "six==1.14.0",
        "text-unidecode==1.3",
        "toml==0.10.0",
        "typed-ast==1.4.0",
        "urllib3==1.25.8",
        "vine==1.3.0",
        "wcwidth==0.1.9",
        "wrapt==1.11.2",
        "xmltodict==0.12.0",
        "zipp==3.1.0",
        "git+ssh://git@bitbucket.org/vivacomsolution/campus-shared-models.git@1.44.0#egg=shared-models-campuscom",
        "git+ssh://git@bitbucket.org/vivacomsolution/campus-libs.git@1.4.0#egg=campus-libs"
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        # "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.7',
)
